namespace DigitalInsights.DB.Common.Enums
{
    public enum EducationSubject
    {
        Agriculture = 0,
        ArchaeologyAndEthnology = 1,
        Architecture = 2,
        ArtAndLiterature = 3,
        Astronomy = 4,
        Bioengineering = 5,
        Biology = 6,
        BusinessOrBusinessAdministration = 7,
        Chemistry = 8,
        CommunicationsJournalismAndWriting = 9,
        ComputerScienceOrInformationSystems = 10,
        Economics = 11,
        Education = 12,
        Engineering = 13,
        EnvironmentalScience = 14,
        Ergonomics = 15,
        FinanceAndAccounting = 16,
        Forestry = 17,
        Geography = 18,
        History = 19,
        HumanResources = 20,
        HumanitiesEthnicAndCulturalStudies = 21,
        Law = 22,
        LibraryAndInformationScience = 23,
        Linguistics = 24,
        LogisticsAndSupplyChain = 25,
        Management = 26,
        Manufacturing = 27,
        Mathematics = 28,
        MedicineAndHealthSciences = 29,
        Military = 30,
        MusiFilmAndDance = 31,
        Philosophy = 32,
        Physics = 33,
        PoliticalScience = 34,
        Psychology = 35,
        PublicAffairs = 36,
        ReligiousStudies = 37,
        SalesAndMarketing = 38,
        Sociology = 39,
    }
}
